// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMVRoDxJij-KDKR4pwIw-VQT6rYv8y-x0',
    appId: '1:170430454912:web:1b2fa486c54f51ce0a9a65',
    messagingSenderId: '170430454912',
    projectId: 'simplechatapp-6fb74',
    authDomain: 'simplechatapp-6fb74.firebaseapp.com',
    storageBucket: 'simplechatapp-6fb74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOPHMRJ_A1Z8O5UoZLX9AH4TBDjhm6Co',
    appId: '1:170430454912:android:20474acc7656d8a90a9a65',
    messagingSenderId: '170430454912',
    projectId: 'simplechatapp-6fb74',
    storageBucket: 'simplechatapp-6fb74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyfzTIQJn0J-JfANpHvhwoud8Ugftlj0',
    appId: '1:170430454912:ios:b10b911c661c4e2b0a9a65',
    messagingSenderId: '170430454912',
    projectId: 'simplechatapp-6fb74',
    storageBucket: 'simplechatapp-6fb74.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoyfzTIQJn0J-JfANpHvhwoud8Ugftlj0',
    appId: '1:170430454912:ios:8b67bd9dae7429380a9a65',
    messagingSenderId: '170430454912',
    projectId: 'simplechatapp-6fb74',
    storageBucket: 'simplechatapp-6fb74.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
